### ISSUE TITLE
This doesn't seems to work. :-\

### ISSUE THREAD

**Issue by NullVoxPopuli** [btecu/ember-cli-bootstrap-datetimepicker#1]
in my controller:

      startTime: new Date(),

in my template (emblem):

        = bs-datetimepicker date=startTime

all that shows up in a text field with the date in it. clicking it doesn't activate the date picker. :-\

Am I missing something?

    "ember": "1.13.7",
    "ember-cli": "1.13.8",
    "ember-cli-bootstrap-datetimepicker": "0.0.4",

**Comment by btecu** [comment]
How did you install the addon?

**Comment by NullVoxPopuli** [comment]
ember install <add-on name>

**Comment by btecu** [comment]
I suppose I didn't specify in the documentation although obvious because of its name - this addon assumes you have `Bootstrap 3`.

Do you have `Bootstrap 3` in your project?

**Comment by NullVoxPopuli** [comment]
ah no. I am using foundation, and thought bootstrap would be included.
sorry!
