### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by prasannatm** [btecu/ember-cli-bootstrap-datetimepicker#10]
This plugin is really awesome where I could use in lot of places in my current Project. Thanks for building that. Is there any way that this could support bootstrap 4 alpha ?

**Comment by btecu** [comment]
I was going to test it when Bootstrap 4 beta was available. Since it's alpha, there are still many changes to do.
However, it should probably work. Have you tried it?

**Comment by btecu** [comment]
Closed for inactivity.
