### ISSUE TITLE
bootstrap-datetimepicker requires Moment.js to be loaded first

### ISSUE THREAD

**Issue by sarus** [btecu/ember-cli-bootstrap-datetimepicker#11]
Installed via ember-cli 

```
ember install ember-cli-bootstrap-datetimepicker
```

and I'm seeing this error when trying to use this component:

```
vendor.js:135832Uncaught bootstrap-datetimepicker requires Moment.js to be loaded first
```

I do have moment included in my package.json.  Do I need to import it as a global?  Is there a way to have it use the `import moment from "npm:moment";` syntax?  I want to avoid including moment through bower and NPM. 

Thanks!

**Comment by btecu** [comment]
Yes, `bootstrap-datepicker` requires `moment.js`. Does your `package.json` contains `ember-cli-moment-shim` and `moment` under its dependencies?

**Comment by sarus** [comment]
Thanks so much!  I didn't have the `ember-cli-moment-shim` installed and just had moment itself installed.  Is there an easy way to override just the icons?  We're not using any of the bootstrap icons although we do use bootstrap itself.

**Comment by btecu** [comment]
You can change the calendar icon and text: `{{bs-datetimepicker iconClasses='material-icons' iconText='face'}}`

**Comment by sarus** [comment]
Thank you for your assistance (and providing this great component).  I see that modifying `iconClasses` changes the calendar icon but is there a way to modify the other icons?

Based on the underlying control it looks like you can provide custom icons for the time, date, up and down arrows.

```
            $('#datetimepicker8').datetimepicker({
                icons: {
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-arrow-up",
                    down: "fa fa-arrow-down"
                }
            });
```

http://eonasdan.github.io/bootstrap-datetimepicker/#custom-icons

**Comment by btecu** [comment]
There is no way currently.

**Comment by sarus** [comment]
Just submitted a PR https://github.com/btecu/ember-cli-bootstrap-datetimepicker/pull/12 to include this capability.  Thanks!

**Comment by avijayaattri** [comment]
hello i also have the same error in my console and i have moment.js file in asset folder but getting the same error i.e 
![error](https://user-images.githubusercontent.com/40054018/41187719-e527c1f4-6bcd-11e8-971f-ee50834c50c1.PNG)

**Comment by btecu** [comment]
@avijayaattri Do you have `ember-cli-moment-shim` in your `package.json`?
