### ISSUE TITLE
DEPRECATION

### ISSUE THREAD

**Issue by amirshakya2010** [btecu/ember-cli-bootstrap-datetimepicker#14]
DEPRECATION: A property of <redact@view:-outlet::ember658> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]

**Comment by btecu** [comment]
This is most likely unrelated to the addon but on how you mutate date somewhere.
You probably change the data being passed to the component before the component has finished rendering.

Could you create a repository with minimal code reproducing this issue?

**Comment by btecu** [comment]
Reopen if you can reproduce.
