### ISSUE TITLE
Cannot find module 'eonasdan-bootstrap-datetimepicker-npm'

### ISSUE THREAD

**Issue by sarus** [btecu/ember-cli-bootstrap-datetimepicker#15]
I noticed that `eonasdan-bootstrap-datetimepicker-npm` is listed as part of `devDependencies` in `package.json`.  As a result, it does not get installed if you install this add on with the typical `npm install && bower install` command.

Should `eonasdan-bootstrap-datetimepicker-npm` be moved to dependencies rather than `devDependencies`?  Otherwise I have to add an exception for this  this addon to use `ember install` as part of our build process.

**Comment by btecu** [comment]
The addons should be installed with `ember install ember-cli-bootstrap-datetimepicker`.
The `git` page states that clearly and it's normal among `ember` addons.
