### ISSUE TITLE
Reseting the date causes JS error

### ISSUE THREAD

**Issue by dmitryt** [btecu/ember-cli-bootstrap-datetimepicker#2]
When user clears entered date, JS error happens.
"Uncaught TypeError: date() parameter must be one of [null, string, moment or Date]"

After some investigations I've found, that it's happened here:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1499-L1501

When date is changed, you handles that event and set the date:
https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/master/addon/components/bs-datetimepicker.js#L26

But newDate = false there, because

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L853-L857

I suggest the easiest fix:
```javascript
this.set('date', newDate || null);
```

**Comment by btecu** [comment]
It seems a bad idea to return false when there's no date.
Irregardless, I'll fix it this weekend.

Thanks for looking into it.

**Comment by btecu** [comment]
This has been fixed.
