### ISSUE TITLE
Should switch to eonasdan-bootstrap-datetimepicker

### ISSUE THREAD

**Issue by nmcclay** [btecu/ember-cli-bootstrap-datetimepicker#20]
The current repo appears to be deprecated in favor of the new one that isn't using the 'npm' suffix:

[eonasdan-bootstrap-datetimepicker-npm](https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker-npm)
[eonasdan-bootstrap-datetimepicker](https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker)

**Comment by btecu** [comment]
Thanks for opening this.
I was tracking the official issue, but it never got updated.
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1438

**Comment by btecu** [comment]
Last version has some major issues. For example:
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1778
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1783

I switched back to the custom version for now.
Please reopen when those get fixed and a new version gets published.

**Comment by nmcclay** [comment]
👍

**Comment by nmcclay** [comment]
This issue seems much more complicated by the fact that ember 2.8 uses jquery 3.0: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1714

**Comment by btecu** [comment]
The two issues above mentioned have been fixed in the last version.
Could use the official repository now.
