### ISSUE TITLE
Getting Error "input.size is not a function" after upgrading to Ember 2.8

### ISSUE THREAD

**Issue by sarus** [btecu/ember-cli-bootstrap-datetimepicker#21]
Started seeing this error after upgrading to Ember 2.8.  Doesn't seem like it would be ember 2.8 related so it might be a coincidence and something else was modified during the upgrade process:

```
app.js:15 Uncaught TypeError: input.size is not a function
dateTimePicker @ bootstrap-datetimepicker.js:2305
(anonymous function) @ bootstrap-datetimepicker.js:2364
each @ jquery.js:368
each @ jquery.js:157
$.fn.datetimepicker @ bootstrap-datetimepicker.js:2359
didInsertElement @ bs-datetimepicker.js:42
superWrapper @ ember.debug.js:24798
```

This is when using the latest `0.3.1` version of ember-cli-bootstrap-datetimepicker.  The only other change I've made to the project is that I started using `ember-moment` as well.

**Comment by sarus** [comment]
Turns out jquery `.size()` was deprecated as of jquery `1.8` and was removed in `3.x` which ember `2.8` started using.  Instead of `.size()` it should use `.length`.  I believe this is an issue with bootstrap-datetimepicker rather than your project.  

This issue seems relevant:

https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726

**Comment by btecu** [comment]
I'd like to switch to the latest version but it has too many issues.
Relevant: https://github.com/btecu/ember-cli-bootstrap-datetimepicker/issues/20

**Comment by sarus** [comment]
Interesting.  For the time being I've rolled back to Ember 2.7.

**Comment by btecu** [comment]
If jQuery is the issue, there's nothing preventing you using Ember 2.8 with jQuery 2.x.

**Comment by nmcclay** [comment]
I fixed this issue by simply extending jQuery:
```
jQuery.fn.extend({
	size: function() {
		return $(this).length;
	}
});
```
I included this in the init hook of a component I had that wrapped the ember-cli-bootstrap-datepicker component and this error disappeared completely running ember v2.8.2.

**Comment by btecu** [comment]
@nmcclay Would this be backwards compatible with jQuery 1 - 2?
