### ISSUE TITLE
Passing an undefined value results in datepicker error

### ISSUE THREAD

**Issue by pijey** [btecu/ember-cli-bootstrap-datetimepicker#24]
Hi and thanks for your addon ! I have a question regarding [this](https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/master/addon/components/bs-datetimepicker.js#L46) line of code :
`
date: this.getWithDefault('date', defaults.defaultDate))
`

The value of defaults.defaultDate in bootstrap datetimepicker is [false](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L2445). When passing an undefined value do the component, I'm having the following error : **date() parameter must be one of [null, string, moment or Date]** which is logical as the date's value is **false**.

IMO passing a undefined value to the component should display an empty datetimepicker. 

I bypassed this issue by manually setting null to the property.

Thanks !

**Comment by btecu** [comment]
Passing `undefined` is not valid in the first place.
As you posted, valid inputs are `null`, `string`, `moment` or `Date`, so you would still get that error even if
 `date: this.getWithDefault('date', defaults.defaultDate))` was `this.get('date')`.

**Comment by pijey** [comment]
Thanks for your response. I think that passing an undefined value shouldn't raise an error, it should be treated as a null value and display an workgin empty datetimepicker. Since the bootstrap datetimepicker is working this way, I'll close the issue. Thanks !

**Comment by btecu** [comment]
I agree with you. The reason is like this is probably because the date time picker just passes the values to `momentjs`.
