### ISSUE TITLE
Pop-up not displaying on Ember 2.9.1 with Bootstrap 3.3.7

### ISSUE THREAD

**Issue by mstate** [btecu/ember-cli-bootstrap-datetimepicker#28]
My issue is that the pop-up calendar does not appear when I click in the input box or when I click the calendar icon.  And, I'm a little baffled as to why not.  Any ideas would be appreciated.  Perhaps it's an Ember 2.9.1/Bootstrap 3.3.7 version issue.  I am using the workaround for JQuery 3.0 to add size.

I would like to leave useful information for troubleshooting, but there's not much.  There are no error messages in the console.  The initial date value I provided appears in the input box.  I've checked and datetimepicker appears to initialize fine and I can see it's properties.  The calendar icon appears.  If I send an undefined date (as opposed to a null date), it I can see an error message from the datetimepicker.js.  

So, everything appears to be "working".  But, the calendar pop-up does not display.

I've tried to initialize another field manually with:
`$('#myfield').datetimepicker(); `
and then toggle on the display with:
`$('#myfield').data('DateTimePicker').toggle();`
and it still does not display the calendar.  The toggle function is available but appears to do nothing.

I'm stumped.  Any suggestions would be greatly appreciated.

**Comment by btecu** [comment]
It might be related to jQuery 3.
Could you provide a demo with the issue?

**Comment by gnazarkin** [comment]
Having the same problem

**Comment by btecu** [comment]
Can you provide a minimal repository with a reproduction?

**Comment by gnazarkin** [comment]
Not sure if I'll be able to get something up quick, but it does insert the elements and I can see them in the inspector but it doesn't show on screen and does't seem like anything should be hiding it
