### ISSUE TITLE
Uncaught TypeError: date() parameter must be one of [null, string, moment or Date]

### ISSUE THREAD

**Issue by jaredgalanis** [btecu/ember-cli-bootstrap-datetimepicker#29]
I have a model with undefined for the value of a date property (it's a create page and my values on all properties to begin with are undefined). When I use this in ember-cli-bootstrap-datetimepicker I get the following error:
```Uncaught TypeError: date() parameter must be one of [null, string, moment or Date]```
Looking at line 50 of the bs-datetimepicker.js file I see that:
```date: this.getWithDefault('date', defaults.defaultDate),```
Is the source of this error. When I ```console.log(defaults.defaultDate)``` I see that the value is false. If in line 50 I replace defaults.defaultDate with null, it works fine, but I suspect this does not handle things as intended in all cases.

**Comment by btecu** [comment]
You probably should report this https://github.com/Eonasdan/bootstrap-datetimepicker, since that error is not coming from this component but from `bootstrap-datetimepicker`.

**Comment by jaredgalanis** [comment]
Are you sure that it's an issue with ```bootstrap-datetimepicker```. I had a quick look at the docs just now and it seems that the default value for defaultDate is false. 
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#defaultdate
So it looks to be behaving as expected unless I'm missing something (which I admit could be the case). But given this, I think the bug is not handling for that scenario on this end.

**Comment by btecu** [comment]
Not quite understand what you're suggesting.
The error is coming from here:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/fba1e544c7b404f0e3dc4873b13f9e12fd657464/src/js/bootstrap-datetimepicker.js#L1511

**Comment by jaredgalanis** [comment]
Sorry for being unclear. So that error is occurring because in the addon we are setting the date property to false - I think that's intended behavior. Because we're grabbing defaultDate, which is false (which is also intended), and setting date equal to that (which is probably not intended), we're getting the assertion. 

I do agree that this is not an unreasonable use case of defaultDate and it might still be worth suggesting a change at the original library repo, but I think the bug is arising due to what is occurring in the addon.

**Comment by btecu** [comment]
Thinking more about it, I think it would be safe to default to `null`. I also have a case where I had to check for `undefined` before passing the date to the component. Can you submit a pull request?

**Comment by jaredgalanis** [comment]
Okay sounds good!
