### ISSUE TITLE
readonly="false" still enables readonly, widget is always disabled

### ISSUE THREAD

**Issue by esistgut** [btecu/ember-cli-bootstrap-datetimepicker#31]
https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/master/addon/templates/components/bs-datetimepicker.hbs#L1

readonly="false" doesn't disable the attribute, this way the widget will always be read-only and disabled.
Related stackoverflow: http://stackoverflow.com/questions/6172911/what-is-the-difference-between-readonly-true-readonly-readonly

**Comment by btecu** [comment]
I'm not able reproduce this issue on a laptop.
What browser / device are you having issues with?

**Comment by esistgut** [comment]
Same behaviour on both Firefox and Chrome (edge versions).
```bash
$ ember --version
ember-cli: 2.10.0
node: 6.9.4
os: linux x64
```
Ember is rendering a DOM like this:
```html
<input readonly="false">
```
so the input is readonly, compliant to W3C standard.
Seems to be related to https://github.com/emberjs/ember.js/issues/11828
A user in the thread links a possible workaround: https://github.com/MarSik/shelves/commit/255c547022638f33412e40e2ee12292787d9d096

**Comment by btecu** [comment]
Can you create a small repository reproducing this issue?

**Comment by btecu** [comment]
This appears not to be related to this addon. Please reopen if you can provide a repository reproducing the issue.
