### ISSUE TITLE
Consider downgrading node version to >= 4 to match ember-cli

### ISSUE THREAD

**Issue by ultimatemonty** [btecu/ember-cli-bootstrap-datetimepicker#39]
Just curious if there is a reason for requiring `>=6` for the node version?

Ember-CLI defaults to `>= 4` and I'm sure more than a few folks are running into issues with this (myself included). v4 won't be EOL'd until [April 2018](https://github.com/nodejs/LTS#lts-schedule).

Thanks!

**Comment by btecu** [comment]
No reason in particular. The changes required to make it compatible should be minimal.
Can you submit a pull request?

**Comment by ultimatemonty** [comment]
sure thing!
