### ISSUE TITLE
Should provide more attributeBindings like id

### ISSUE THREAD

**Issue by vasilakisfil** [btecu/ember-cli-bootstrap-datetimepicker#4]
Id is necessary for appointing labels to the input.

**Comment by btecu** [comment]
Are you able to submit a PR?

**Comment by vasilakisfil** [comment]
yeap I can handle this.

**Comment by btecu** [comment]
@vasilakisfil ping.

**Comment by btecu** [comment]
I think `Ember` should the one taking care of the `id`.
