### ISSUE TITLE
how to set date format based on browser locale?

### ISSUE THREAD

**Issue by sowmyarangineni** [btecu/ember-cli-bootstrap-datetimepicker#46]
Format = 'L'  throws an error. I want to render the date in the users locale and not hard code to a specific format.

**Comment by btecu** [comment]
What is the error?

**Comment by sowmyarangineni** [comment]
oops my bad there isn't an error, but is does not show the set date . 
  {{bs-datetimepicker
    date=args.revision.effectiveDate
    format='L'
    disabled=(eq args.revision.status 'Published')
    updateDate=(action "onDateChange" 'effectiveDate')}}

**Comment by btecu** [comment]
Can you please set the reproduction code in a repository so I can take I look?

**Comment by btecu** [comment]
Closed due to inactivity.
