### ISSUE TITLE
Trigger action when date changes or focus is lost

### ISSUE THREAD

**Issue by hectorsq** [btecu/ember-cli-bootstrap-datetimepicker#52]
I am using ember-cli-bootstrap-datetimepicker inside a component.  

When I select a date or time in the popup, my internal value is changed as expected. When I leave the field, I want to send the date time value to the server.

I have this working for simple input fields.
```handlebars
{{!-- string-field.hbs --}}
<div class="form-group">
  <label>{{observation.name}}</label>
  {{ input class="form-control" type="text"
     value=observation.stringValue focus-out=(action 'lostFocus') }}
</div>
```

However I cannot make this work for a bs-datetimepicker field

```handlebars
{{!-- datetime-field.hbs --}}
<div class="form-group">
  <label>{{observation.name}}</label>
  {{ bs-datetimepicker date=observation.datetimeValue focus-out=(action 'lostFocus')}}
</div>
```

I also tried to add a change action in my component but it is not fired when the date changes.

Any suggestions?

**Comment by btecu** [comment]
Currently not supported by the addon.

It doesn't make much sense either.

https://github.com/Eonasdan/bootstrap-datetimepicker doesn't have an event for this either.

What could be done is extend the HTML input adding an `onblur` event that calls an `onBlur` action here: https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/master/addon/templates/components/bs-datetimepicker.hbs#L2
