### ISSUE TITLE
Fails with Ember 3 and Bootstrap 4

### ISSUE THREAD

**Issue by belgoros** [btecu/ember-cli-bootstrap-datetimepicker#53]
I tried to use it with Ember 3 and Bootstrap 4 and unfortunately failed to display it correctly:
```
# templates/working-hours.hbs

<div class="form-group col-sm-4">
    {{bs-datetimepicker date='13-04-2018' showClear=true format='HH:mm'}}
</div>
```
Do I use the correct syntax ? Nothing but a textfield is displayed:

<img width="420" alt="screen shot 2018-04-13 at 14 45 18" src="https://user-images.githubusercontent.com/83579/38735547-5f777e8a-3f29-11e8-890b-fb3b7cbf2548.png">

Another point is that, the add-on uses `glyphicon glyphicon-calendar` icon which is not available with **Bootstrap 4** (they are extracted icons and advise to use some [external libraries](https://getbootstrap.com/docs/4.0/extend/icons/).
My config:
```
ember-cli: 3.0.0
node: 8.9.1
os: darwin x64
```

**Comment by btecu** [comment]
It should work with Bootstrap 3 but not with Bootstrap 4 - see requirements list.

Can you put together a small repository reproducing the issue?

**Comment by btecu** [comment]
You're passing a date (no time) yet  your format is only for the time?

**Comment by belgoros** [comment]
I'd like to pick a time only, unfortunately there was no example in `README`. I'll push a simple app to show an example later this evening. Thank you.

**Comment by belgoros** [comment]
I pushed an [example](https://github.com/belgoros/time_picker) app. If you have time, you can observe the behaviour. Thank you.

**Comment by btecu** [comment]
Yes, it will not work with Bootstrap 4.

Just to test, in your `index.html` add this line after your css lines:
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">`


The value is `date`, not `time`. You can't just pass any string.
Add a property on the controller. `time: new Date()` and then in the template `date=time`.


You should see an icon you can press on to open it and the hour (current) should be there.

You can also set `openOnFocus=true` to open when you click on the field.

All this is documented.
