### ISSUE TITLE
missing jquery error with ember-source 3.4

### ISSUE THREAD

**Issue by csantero** [btecu/ember-cli-bootstrap-datetimepicker#55]
After upgrading my app to ember-source 3.4, I'm now getting a runtime error from `bootstrap-datetimepicker.js`: `bootstrap-datetimepicker requires jQuery to be loaded first`. I've already followed the instructions at `https://github.com/emberjs/ember-jquery`, and `$` is defined globally, but a `jQuery` variable is not available for this script. `bootstrap-datetimepicker.js` has code to load jQuery (and moment) as an AMD module, so is there a way we can configure this addon to provide jQuery that way instead of via the global?

**Comment by btecu** [comment]
@csantero could you setup a small repository with this issue for me to take a look at?

**Comment by csantero** [comment]
@btecu Here you go: https://github.com/csantero/bs-dtp-jq-error-demo

Just fire up the tests and you should see the error.

**Comment by csantero** [comment]
@btecu Sorry about that. For some reason I forgot to actually repeat those commands in the demo project before linking it, but I have I definitely have run them in my production project and am still getting the error there. I'll see if I can come up with an actual reproduction.

**Comment by csantero** [comment]
@btecu I've determined that my problem comes from a strange interaction with other addons and has nothing to do with ember-cli-bootstrap-datetimepicker. Sorry for wasting your time, and thanks for this great addon!
