### ISSUE TITLE
minDate is assigned to Default Date

### ISSUE THREAD

**Issue by sohel003** [btecu/ember-cli-bootstrap-datetimepicker#6]
If I provide the minDate value, it assign this value to default date. 
While creating a new record, it creates a bug. 
I wonder if it is possible to show blank as default value in calendar.

**Comment by btecu** [comment]
Do you think you could create a small repository demonstrating this issue?

**Comment by btecu** [comment]
I've published a new version (`0.0.6`) that probably fixes your issue.

**Comment by sohel003** [comment]
hay, I will check with new version. I have checked the bootstrap documentation (http://eonasdan.github.io/bootstrap-datetimepicker/Options/).. As per the documentation of minDate, 'minDate will override defaultDate and useCurrent'. So it seems to me that bootstrap considers it a feature. But in my case, it is actually a bug. I will check your new version if fixed it manually..

**Comment by sohel003** [comment]
Closing the issue as it seems bootstrap issue
