### ISSUE TITLE
Dependency on a feature branch

### ISSUE THREAD

**Issue by GramozKrasniqi** [btecu/ember-cli-bootstrap-datetimepicker#65]
https://github.com/btecu/ember-cli-bootstrap-datetimepicker/blob/486b0edde734170ab0118c2ec6a3aefcb63040fa/package.json#L37

Please remove the dependency on the branch.
You can fork the project make the changes and release it as a own package till the fix is completed.

**Comment by btecu** [comment]
What's wrong with depending on a branch?

**Comment by GramozKrasniqi** [comment]
*Branches used in this case like a feature branch or bug fix brach are unstable.
They can be deleted they dont have a long life span.
*Manuall process of integrating bugfixes or new features from upstream branch.
*Making consumers dependent on github as an artifact store (most internal apps use internal aritfacts store like nexus to act as a cache for npm packeges from npmjs) they dont have access to the internet.
We just found out that our build was failing beqcuse it couldnt get the dependent package.

Github is not an artifact store.
While it is fine to have a dependecy on a branch while work is in progress releasing the package with that dependecy is not.

**Comment by btecu** [comment]
Fixed in [0.8.3](https://github.com/btecu/ember-cli-bootstrap-datetimepicker/releases/tag/0.8.3)
