### ISSUE TITLE
BTECU dependency version issue?

### ISSUE THREAD

**Issue by hornetnz** [btecu/ember-cli-bootstrap-datetimepicker#66]
We've been having an issue with our build recently, getting and error 

> 14:57:11  The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
14:57:11  Error: ENOENT: no such file or directory, open '/var/build/workspace/ber-engine-contacts_CustomFields/tmp/source_map_concat-input_base_path-fT3qcw5h.tmp/node_modules/btecu-eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js'

When I looked into it more, I noticed the version dependencies for btecu-eonasdan-bootstrap-datetimepicker were at 4.17.48, which matches what NPM shows [here](https://libraries.io/npm/btecu-eonasdan-bootstrap-datetimepicker), yet their repo shows the latest release as .47 ([here](https://github.com/Eonasdan/bootstrap-datetimepicker/releases)).

I'm guessing I should make a similar issue ticket on that repo, but you may want to pin this back to .47?

**Comment by btecu** [comment]
`btecu-eonasdan-bootstrap-datetimepicker` includes some fixes on top of `Eonasdan/bootstrap-datetimepicker` which is why is a different version.

Can you try deleting your `node_modules` folder and running `yarn` / `npm`?

**Comment by hornetnz** [comment]
...so the npm download has code that's modified from the repo that it itself links to???

The above error is coming back on a Jenkins build (although we've randomly seen it locally as well), so the Jenkins workspace should be clear at the start of each build.

**Comment by hornetnz** [comment]
FWIW, I got the build working as we found a mismatched ember-cli version in the package files between the couple of repos.
However, my confusion of why NPM reports .48 and this repo package file is at .47 is still in question.

**Comment by btecu** [comment]
Should be fixed in version `0.9.0`.
