### ISSUE TITLE
disabled=true support?

### ISSUE THREAD

**Issue by dbinetti** [btecu/ember-cli-bootstrap-datetimepicker#67]
Forgive me for such a noob question, but is it possible to disable the component as in `disabled=true`?  I'm trying to create a UI where the element doesn't visually change, but editing the value is not possible (based on permissions).  I've tried a number of variants and can't find anything in the repo itself...  

thanks

**Comment by btecu** [comment]
It doesn't currently. It should not be too complicated to add support for it. Do you mind submitting a pull request?

**Comment by dbinetti** [comment]
I would love to, but I'm afraid I don't have the ability.  I really don't know Javascript and am mostly cargo-culting.  If there is anything in my ability to help (documentation, etc.) then I would gladly do so, but I really don't even know where to begin submitting a PR for this...

**Comment by btecu** [comment]
Version `0.9.0` now supports `disabled`.

**Comment by dbinetti** [comment]
Many thanks @btecu .  I wish I had been able to ease this through a PR; your efforts are most appreciated.
