### ISSUE TITLE
calendarWeeks and viewMode options

### ISSUE THREAD

**Issue by poplevente** [btecu/ember-cli-bootstrap-datetimepicker#83]
Hi all,

for whatever reason the calendarWeeks and viewMode options don't seem to do anything. do you know the cause?

thanks!

**Comment by btecu** [comment]
Are the options not passed in to the actual library?
Can you verify that the values are correct and test the library with your values?
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#calendarweeks

**Comment by poplevente** [comment]
Never mind, it was my fault. i had another calendar component which was incompatible and the 2 was mixed and that's why it didn't work :)
