### ISSUE TITLE
Possibility to click on weeks

### ISSUE THREAD

**Issue by poplevente** [btecu/ember-cli-bootstrap-datetimepicker#84]
Hi there,

is there a possibility to make the weeknumbers clickable?
And have them to be disabled in certain situations?

**Comment by btecu** [comment]
Is that something supported by http://eonasdan.github.io/bootstrap-datetimepicker?

**Comment by poplevente** [comment]
no i don't think so, that's why i asked :)

**Comment by poplevente** [comment]
never mind, i'll implement something simple we need. thanks!
