### ISSUE TITLE
Date Picker not working with Ember 3.13

### ISSUE THREAD

**Issue by SebastianPetric** [btecu/ember-cli-bootstrap-datetimepicker#85]
Since I upgraded the project to ember-cli 3.13, the date picker is not showing anymore (See Screenshot). Time Picker is still working. No error messages are showing in console. I tried using version 0.9.1 (which was working before the upgrade) and 0.9.2. Both don't work.

![image](https://user-images.githubusercontent.com/4921411/97418762-7ac40980-1909-11eb-9dce-54faf6ccc7bc.png)
![image](https://user-images.githubusercontent.com/4921411/97418790-83b4db00-1909-11eb-9da9-4fac7e1e98a3.png)

The component I implemented:
<BsDatetimepicker @id="control_datetimepicker_start" @date={{startDate}} @locale={{locale}} @class="xc_deliveries-dtpicker" @maxDate={{maxStartDate}} @change={{action "changeFrom"}} />

**Comment by btecu** [comment]
It should probably be like this:
```hbs
<BsDatetimepicker
  class="xc_deliveries-dtpicker" 
  @date={{startDate}}
  @locale={{locale}}
  @maxDate={{maxStartDate}}
  @change={{action "changeFrom"}}
/>
```

Note:
 - `class` might not do what you want
 - `date` and `locale` should be lower case
 - in a `glimmer/component` you should also use `this` or `@`, i.e., `{{this.startDate}}` or `{{@startDate}}`
 - Bootstrap is still required

If you're still having issues, please create an Ember Twiddle or a repository reproducing the issue.
